import { useRouter } from "next/router";
import React, { useEffect, useState } from "react";
import Head from "next/head";
import Image from 'next/image';
import Footer from "../components/Footer";
import Header from "../components/Header";
import { collection, doc, getDoc, getDocs, query } from "firebase/firestore";
import { db } from "../firebaseConfig";
import InfoCard from "../components/InfoCard";

export default function Class() {

  //const {img, name,  type, description, ratings, address, price, category} = router.params;


  const [data, setData] = useState([])
  const [loading, setLoading] = useState(false)

  const router = useRouter();
  const fetch = async (id) => {
    setLoading(true)
    if (id) {
      const docRef = doc(db, "classes", id);
      const docSnap = await getDoc(docRef);
      const data = docSnap.data()
      setData(data)
      setLoading(false)
    } else {
      console.log("id null");
      setLoading(false)
    }

  }

  useEffect(() => {
    if (!router.isReady) return;
    const { id } = router.query
    fetch(id)
  }, [router.isReady, router.query])


  return (
    <div>
      <Head>
        <title>pocketclass</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pc_favicon.ico" />
      </Head>
      {/* header */}
      <Header />

      {/* body */}
      <main className="max-w-7xl mx-auto px-8 py-8 sm:px-16">
        {
          loading ?
            <section>
              <h1>Loading</h1>
            </section>
            :
            <>
              <InfoCard
                key={data.id} // should have an id
                type={data.Type}
                latitude={data.latitude}
                name={data.Name}
                images={data.Images}
                description={data.Description}
                longitude={data.longitude}
                ratings={[data.Ratings]}
                address={data.Address}
                price={data.Price}
                category={data.Category}
              />
            </>
          // <section>
          //   <img className="w-[30%] block mx-auto" src={data.Images} alt="" />
          //   <h2 className="text-4xl font-semibold py-5">
          //     {data.Name}
          //   </h2>
          //   <div className="small flex">
          //     <p className="font-bold">{data.Category}</p>
          //     <p className="font-bold mx-3">{data.Type}</p>
          //   </div>
          //   <p className="">
          //     {data.Description}
          //   </p>
          // </section>
        }
      </main>
      <Footer />
    </div>
  );



  // export default Class;
}


// export async function getStaticProps() {
//   const router = useRouter();
//   const { id } = router.query
//   const docRef = doc(db, "classes", id);
//   const docSnap = await getDoc(docRef);
//   const data = docSnap.data()

//   return {
//     props: {
//       data
//     },
//   };
// }
