import React from "react";
import Footer from "/components/Footer";
import Header from "/components/Header";
import Head from "next/head";
import Image from "next/image";
import Link from 'next/link';

export default function AboutUs() {
  return (
    <div>
      <Head>
        <title>pocketclass</title>
        <meta
          name="terms and conditions"
          content="Generated by create next app"
        />
        <link rel="icon" href="/pc_favicon.ico" />
      </Head>
      {/* header */}
      <Header />

      {/*body*/}
      <main className="max-w-7xl mx-auto px-8 py-8 sm:px-16">
        <section>
          <h1 className="text-4xl font-semibold py-5">About Us</h1>
          <div className="relative h-96 min-w-[300px]">
            <Image
              src="https://links.papareact.com/4cj"
              layout="fill"
              objectFit="cover"
              className="rounded-2xl"
            />
          </div>
          <div className="mt-10 mb-10">
            <p className="text-lg text-gray-700">
              PocketClass is transforming the extracurriculars industry by
              bringing community sports, arts, and music lessons into one
              accessible platform.
              <br></br>
              <br></br>
              Research shows that kids’ participation in extracurricular
              activities is linked to improved health and wellbeing. Benefits
              include improved mental health, stronger sense of peer belonging,
              higer resilience and self-confidence, and higher levels of
              academic achievement over time.
              <br></br>
              <br></br>
              Our mission is to help children and youth discover their passions
              by connecting parents and guardians to a world of
              extracurriculars. There’s not enough time in a day for busy
              parents– so we make it easy and efficient to explore the options
              that align with your life.
              <br></br>
              <br></br>
              
            </p>
            <div className="italic text-lg">
              Signed <span className="text-logo-red font-bold cursor-pointer hover:scale-105 transition transform duration-200 ease-out"><Link href='https://www.linkedin.com/in/andrew-liu545454/'>Andrew</Link></span> & <span className="text-logo-red font-bold cursor-pointer hover:scale-105 transition transform duration-200 ease-out"><Link href='https://www.linkedin.com/in/lisahuh/'>Lisa</Link></span>
              </div>
          </div>
        </section>
      </main>
      <Footer />
    </div>
  );
}
